### PR TITLE
Fonts sorted by family name

### LINKED ISSUE #5: Canvas font panel should display fonts in a hierarchy.
Currently all the fonts are in one big list. They should be sorted by family and allow drilling down for individual typefaces.

### PR DESCRIPTION
**Pull request by samgreen**
screen shot 2013-11-04 at 3 30 30 pm
screen shot 2013-11-04 at 3 30 42 pm

This resolves #5.

We may want to merge these changes instead to a `WDFontFamiliesController` just for clarity. This version is working but doesn’t have a clean separation of concerns. Additionally it might be simpler to still display all fonts and use a grouped table view with headers of family names. 

We also need to figure out how we should rewrite `scrollToSelectedFont`. Should we scroll to the selected font's family? Should we automatically show only fonts in that family and scroll to the font?

Based on where we merge these changes should possibly be integrated to the `WDFontLibraryController` as well. But I didn't want to do that until we have the first implementation ironed out.

### CODE REVIEW

**Comment by sprang** [comment]
I haven't had a chance to really look at this yet, but I was wondering if we could have two tables side by side (family on left, typeface on right)? I like to avoid interfaces where you have to drill down if possible. Especially in this case where you might be going back and forth a lot.

We could probably tighten up the row height quite a bit, so the fonts could be smaller and the tables narrower.

It would also be nice if the font family was rendered in one of its typefaces, but  maybe that's not a big deal.

**Comment by samgreen** [comment]
Easy changes. Will do.

**Comment by samgreen** [comment]
Preview of changes:

screen shot 2013-11-05 at 11 20 16 am

**Comment by sprang** [comment]
Hmm, I think that's too ginormous. This is what I was thinking, but maybe it's not feasible with touch constraints:

font mockup

**Comment by samgreen** [comment]
What do you think of this?

screen shot 2013-11-05 at 2 36 57 pm

**Comment by samgreen** [comment]
I also have another idea I'd like to try if you're not sold on this layout.

**Comment by samgreen** [comment]
Tweaks. What do you think of this? I still plan to make the header labels custom fonts.

screen shot 2013-11-05 at 3 15 27 pm

**Comment by sprang** [comment]
The previous screenshot is on the right track. My intention for this change was to make the list of fonts more manageable, which adding the headers does not achieve. The list gets even longer in that case.

I think the typeface side should drop the font name. So it's just "Bold", "Semibold", etc. Row heights and font sizes should be the same in both tables. I think the tables would look better with some space around them, perhaps a light gray layer border, and maybe no separators.

I'm happy to tweak the appearance to my liking if you want to focus on the implementation details. I usually have to fiddle around a lot to get something I like, and I suspect doing that via GitHub comments is not very efficient. :-)

**Comment by sprang** [comment]
Finally got a chance to play with this. Unfortunately, it's crashing for me at the moment.

**Comment by samgreen** [comment]
Can you give me any additional info? Stack trace?

**Comment by sprang** [comment]
Very strange. It was crashing releasing a CTFontRef, but I can't reproduce it now.

I'm seeing the original version with the large tables side by side (3 screenshots back) though. Is that expected?

**Comment by sprang** [comment]
Do you want me to take this and run with it now? I should have time to polish it up today and tomorrow. I don't want to step on your toes if you're still working on it though.

**Comment by samgreen** [comment]
Run with it. The latest version is now pushed. I did the latest screenshot from a test branch so that code is scrapped.

**Comment by sprang** [comment]
Working on it now. I see that the crash I mentioned doesn't happen in the simulator, but it does occur on a real iPad.

**Pull request merged**
