### PR TITLE
Spanish localizable strings added

### PR DESCRIPTION
**Pull request by migdus**
Here's a new branch with the spanish localization. Everything else is untouched.

### CODE REVIEW

**Comment by sprang** [comment]
Awesome. Thanks!

**Comment by sprang** [comment]
Any chance that you'd have time within the next week or so to translate the help to Spanish too?

**Comment by migdus** [comment]
Sure, I'll do it.

**Comment by sprang** [comment]
Hi Miguel, I don't have your email address. Could you contact me at: scs@stevesprang.com? I have 8 new strings that need to be translated to Spanish.

**Pull request merged**
